workflows:
  android-build:
    name: Legion 6 Android
    max_build_duration: 60
    environment:
      flutter: stable

    scripts:
      - name: Create Android project files
        script: |
          flutter create .

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build Android APK
        script: |
          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
